from __future__ import annotations
from typing import Dict, List, Tuple
from DmxFixture import DmxFixture
from PaletteManager import PaletteManager

class YamlPixelStripFixture(DmxFixture):
    """
    A multi-pixel LED strip fixture.
    Maps an array of pixels to colors generated by PaletteManager.
    Configurable:
      - start_channel (dmx_address)
      - pixel_count (number of pixels)
      - color_order (e.g., 'rgb', 'grb', 'brg', etc.)
    """
    def __init__(self, name: str, palette_id: str, start_channel: int,
                 pixel_count: int, color_order: str, palette_mgr: PaletteManager):
        super().__init__(name=name, hue_light_id="__palette__", dmx_address=start_channel)
        self.palette_id = palette_id
        self.pixel_count = pixel_count
        self.color_order = color_order.lower().strip()
        self._length = pixel_count * 3
        self.palette_mgr = palette_mgr

    def get_dmx_message(self, offset: float = 0.0) -> bytes:
        frame = bytearray(self._length)
        cfg = self.palette_mgr._palettes.get(self.palette_id)
        max_dist = cfg.max_distance if cfg else 100
        
        for i in range(self.pixel_count):
            if self.pixel_count > 1:
                dist = i * (max_dist - 1) / (self.pixel_count - 1)
            else:
                dist = 0.0
                
            r, g, b = self.palette_mgr.get_color_for(self.palette_id, dist, offset=offset)
            
            idx = i * 3
            if self.color_order == "grb":
                frame[idx] = g
                frame[idx+1] = r
                frame[idx+2] = b
            elif self.color_order == "rgb":
                frame[idx] = r
                frame[idx+1] = g
                frame[idx+2] = b
            elif self.color_order == "brg":
                frame[idx] = b
                frame[idx+1] = r
                frame[idx+2] = g
            elif self.color_order == "bgr":
                frame[idx] = b
                frame[idx+1] = g
                frame[idx+2] = r
            elif self.color_order == "gbr":
                frame[idx] = g
                frame[idx+1] = b
                frame[idx+2] = r
            else: # fallback to rgb
                frame[idx] = r
                frame[idx+1] = g
                frame[idx+2] = b
                
        return bytes(frame)
